# Interfaces to have DHCP on
interface=usb0

# DHCP address ranges and lease times
dhcp-range=10.78.10.10,10.78.10.150,12h

# Disable route advertisments. We don't want the other end to start routing packets through us
dhcp-option=3
